/** @deprecated Prefer @/lib/landing/vision2030Styles — Steve Jobs × 2030 SSOT */
export {
  VISION_CTA_ACCENT as BRICLOG_CTA_PILL,
  VISION_CTA_ACCENT as GREEN_CTA_SOLID,
  VISION_CTA_OUTLINE as GREEN_CTA_OUTLINE,
  VISION_DEVICE_TAB_ACTIVE as DEVICE_TAB_ACTIVE,
  VISION_DEVICE_TAB_IDLE as DEVICE_TAB_IDLE,
} from "@/lib/landing/vision2030Styles";
