/**
 * @deprecated — MASTER ENGINE V12 (contentIntelligenceV12.js)
 */
export {
  MASTER_ENGINE_V12_PIPELINE as CONTENT_INTELLIGENCE_V5_PIPELINE,
  MASTER_ENGINE_V12_RULES as CONTENT_INTELLIGENCE_V5_RULES,
  MASTER_ENGINE_V12_BANNED_USER_PHRASES as CONTENT_INTELLIGENCE_V5_BANNED_USER_PHRASES,
} from "./contentIntelligenceV12";
