/**
 * @deprecated — MASTER ENGINE V12 (contentIntelligenceV12.js)
 */
export {
  MASTER_ENGINE_V12_PIPELINE as MASTER_ENGINE_V11_PIPELINE,
  MASTER_ENGINE_V12_RULES as MASTER_ENGINE_V11_RULES,
  MASTER_ENGINE_V12_BANNED_USER_PHRASES as MASTER_ENGINE_V11_BANNED_USER_PHRASES,
  MASTER_ENGINE_V12_DATA_PRIORITY as MASTER_ENGINE_V11_DATA_PRIORITY,
  isGoogleSearchEnabledInV12 as isGoogleSearchEnabledInV11,
  isGeminiConfigured,
} from "./contentIntelligenceV12";
