/** 30초 맛보기 — 회전용 예시 풀 (validateForm 통과) */
export const QUICK_DEMO_POOL = [
  {
    brandName: "모카하우스",
    region: "서울 마포",
    topic: "봄 시즌 신메뉴와 원두 추천",
    mainKeyword: "마포 카페",
  },
  {
    brandName: "라벤더뷰티",
    region: "서울 강남",
    topic: "여름 앞두고 시술 후 관리 팁",
    mainKeyword: "강남 피부관리",
  },
  {
    brandName: "해맑은학원",
    region: "경기 성남",
    topic: "방학 특강 모집과 학습 루틴 안내",
    mainKeyword: "성남 수학학원",
  },
  {
    brandName: "꽃담",
    region: "부산 해운대",
    topic: "어버이날 꽃다발 예약과 배송 안내",
    mainKeyword: "해운대 꽃집",
  },
  {
    brandName: "바람언덕펜션",
    region: "강원 평창",
    topic: "여름 휴가철 조용한 숙소 소개",
    mainKeyword: "평창 펜션",
  },
  {
    brandName: "서울바른치과",
    region: "서울 서초",
    topic: "정기 검진과 충치 예방 상담 안내",
    mainKeyword: "서초 치과",
  },
  {
    brandName: "한옥마을식당",
    region: "전주 완산",
    topic: "지역 재료로 만든 점심 코스 소개",
    mainKeyword: "전주 한옥맛집",
  },
  {
    brandName: "핏스테이션",
    region: "서울 송파",
    topic: "직장인 저녁 PT 체험 프로그램",
    mainKeyword: "송파 헬스장",
  },
  {
    brandName: "오븐앤버터",
    region: "대구 수성",
    topic: "시그니처 빵과 시즌 디저트 라인업",
    mainKeyword: "수성 베이커리",
  },
  {
    brandName: "멍멍살롱",
    region: "인천 연수",
    topic: "여름철 반려견 미용 예약 안내",
    mainKeyword: "연수 애견미용",
  },
  {
    brandName: "맑은눈안과",
    region: "서울 영등포",
    topic: "건조한 계절 눈 건강 관리 팁",
    mainKeyword: "영등포 안과",
  },
  {
    brandName: "요가온",
    region: "서울 용산",
    topic: "초보자를 위한 저녁 요가 클래스",
    mainKeyword: "용산 요가원",
  },
  {
    brandName: "든든이사",
    region: "경기 고양",
    topic: "이사 견적과 포장 서비스 안내",
    mainKeyword: "고양 이사업체",
  },
  {
    brandName: "우드라인",
    region: "서울 성수",
    topic: "거실 인테리어 상담과 시공 사례",
    mainKeyword: "성수 인테리어",
  },
  {
    brandName: "홉가든브루",
    region: "서울 홍대",
    topic: "신규 수제맥주와 페어링 메뉴",
    mainKeyword: "홍대 수제맥주",
  },
  {
    brandName: "비노테라스",
    region: "서울 이태원",
    topic: "와인 페어링 디너 예약 안내",
    mainKeyword: "이태원 와인바",
  },
  {
    brandName: "스냅스튜디오",
    region: "서울 종로",
    topic: "가족 프로필 촬영 시즌 할인",
    mainKeyword: "종로 사진스튜디오",
  },
  {
    brandName: "하늘정원웨딩",
    region: "경기 용인",
    topic: "가을 야외 웨딩 상담 일정",
    mainKeyword: "용인 웨딩홀",
  },
  {
    brandName: "글로우피부과",
    region: "서울 강서",
    topic: "피부 톤 관리 시술 전후 주의사항",
    mainKeyword: "강서 피부과",
  },
  {
    brandName: "튼튼정형외과",
    region: "부산 부산진",
    topic: "운동 후 무릎 통증 상담 안내",
    mainKeyword: "부산 정형외과",
  },
  {
    brandName: "꿈나무어린이집",
    region: "대전 유성",
    topic: "신입 원아 모집과 적응 프로그램",
    mainKeyword: "유성 어린이집",
  },
  {
    brandName: "영어탑",
    region: "서울 노원",
    topic: "내신 대비 스피킹 특강 안내",
    mainKeyword: "노원 영어학원",
  },
  {
    brandName: "클래식바버",
    region: "서울 을지로",
    topic: "남성 헤어 스타일링 시즌 트렌드",
    mainKeyword: "을지로 바버샵",
  },
  {
    brandName: "네일포인트",
    region: "경기 수원",
    topic: "여름 네일 아트 컬렉션 소개",
    mainKeyword: "수원 네일샵",
  },
  {
    brandName: "샤인카워시",
    region: "인천 부평",
    topic: "장마철 실내 세차 패키지",
    mainKeyword: "부평 세차장",
  },
  {
    brandName: "별밤캠핑",
    region: "충북 제천",
    topic: "가족 캠핑장 시설과 예약 안내",
    mainKeyword: "제천 캠핑",
  },
  {
    brandName: "바다향횟집",
    region: "강원 속초",
    topic: "당일 조업 회와 코스 메뉴",
    mainKeyword: "속초 횟집",
  },
  {
    brandName: "책방산책",
    region: "서울 북촌",
    topic: "이달의 추천 도서와 북토크",
    mainKeyword: "북촌 서점",
  },
  {
    brandName: "작은극장",
    region: "서울 대학로",
    topic: "이번 달 공연 일정과 예매 안내",
    mainKeyword: "대학로 연극",
  },
  {
    brandName: "휴스테이모텔",
    region: "경남 창원",
    topic: "출장객을 위한 장기 숙박 혜택",
    mainKeyword: "창원 모텔",
  },
  {
    brandName: "달콤타르트",
    region: "광주 동구",
    topic: "기념일 맞춤 케이크 주문 안내",
    mainKeyword: "광주 케이크",
  },
  {
    brandName: "한의원그린",
    region: "서울 은평",
    topic: "환절기 면역 관리 한방 상담",
    mainKeyword: "은평 한의원",
  },
  {
    brandName: "아이스크림팩토리",
    region: "제주 제주시",
    topic: "여행객을 위한 시그니처 맛 소개",
    mainKeyword: "제주 아이스크림",
  },
  {
    brandName: "그린핀골프아카데미",
    region: "경기 안양",
    topic: "초보 레슨 패키지와 이용 시간",
    mainKeyword: "안양 골프연습장",
  },
  {
    brandName: "플라워클래스",
    region: "서울 성북",
    topic: "원데이 플라워 클래스 모집",
    mainKeyword: "성북 꽃공예",
  },
  {
    brandName: "수영장블루",
    region: "울산 남구",
    topic: "어린이 수영 강습반 개강 안내",
    mainKeyword: "울산 수영장",
  },
  {
    brandName: "타코리코",
    region: "서울 건대",
    topic: "신메뉴 타코와 해피아워 안내",
    mainKeyword: "건대 멕시칸",
  },
  {
    brandName: "비건베이커",
    region: "서울 연남",
    topic: "글루텐프리 빵 라인업 소개",
    mainKeyword: "연남 비건베이커리",
  },
  {
    brandName: "렌탈클린",
    region: "세종 조치원",
    topic: "사무실 정수기·공기청정기 렌탈 혜택",
    mainKeyword: "세종 렌탈",
  },
  {
    brandName: "드론촬영랩",
    region: "경기 파주",
    topic: "매장 홍보용 드론 영상 패키지",
    mainKeyword: "파주 영상제작",
  },
  {
    brandName: "반찬가게온",
    region: "서울 노량진",
    topic: "직장인 도시락 반찬 세트",
    mainKeyword: "노량진 반찬",
  },
  {
    brandName: "키즈카페플레이",
    region: "경기 김포",
    topic: "방학 특별 이벤트와 이용 요금",
    mainKeyword: "김포 키즈카페",
  },
  {
    brandName: "전기차충전소",
    region: "대전 서구",
    topic: "충전 요금과 야간 할인 안내",
    mainKeyword: "대전 EV충전",
  },
  {
    brandName: "로컬마켓",
    region: "전남 순천",
    topic: "지역 농산물 직거래 장터 소식",
    mainKeyword: "순천 로컬푸드",
  },
  {
    brandName: "피아노하우스",
    region: "서울 목동",
    topic: "성인 취미 피아노 레슨 체험",
    mainKeyword: "목동 피아노학원",
  },
];
