/** @deprecated — lib/brand/copy.js 사용 */
export {
  BRAND_META_DESCRIPTION,
  BRAND_META_TITLE,
  BRAND_PHILOSOPHY,
  BRAND_TAGLINE,
  BRICLOG_SLOGAN,
  BRICLOG_SLOGAN_SHORT,
  SITE_FOOTER_DESCRIPTION,
  SITE_FOOTER_TAGLINE,
} from "./copy";
