/** 해외 SaaS 스타일 원클릭 시작 프리셋 */
export const QUICK_PRESETS = [
  {
    id: "flower-season",
    label: "꽃집 · 시즌",
    businessType: "product",
    industry: "flower",
    purpose: "season",
    tone: "emotional",
    region: "서울 강남구",
    brandName: "달빛꽃상자",
    mainKeyword: "강남 꽃다발",
    subKeyword: "기념일, 어버이날",
  },
  {
    id: "cafe-visit",
    label: "카페 · 방문",
    businessType: "space",
    industry: "cafe",
    purpose: "visitDrive",
    tone: "lifestyle",
    region: "서울 성수동",
    brandName: "모카하우스",
    mainKeyword: "성수 카페",
    subKeyword: "브런치, 데이트",
  },
  {
    id: "hospital-info",
    label: "병원 · 안내",
    businessType: "space",
    industry: "hospital",
    purpose: "info",
    tone: "medical",
    region: "서울 서초구",
    brandName: "맑은내과의원",
    mainKeyword: "서초 피부과",
    subKeyword: "상담, 검진",
    excludePhrases: "완치, 100%, 최고",
  },
  {
    id: "furniture-brand",
    label: "가구 · 브랜드",
    businessType: "product",
    industry: "furniture",
    purpose: "brand",
    tone: "premium",
    region: "경기 성남시",
    brandName: "우드라인",
    mainKeyword: "성남 가구 쇼룸",
    subKeyword: "인테리어, 소파",
    storeFeatures: "넓은 쇼룸, 1:1 상담, 주차 가능",
  },
  {
    id: "restaurant-open",
    label: "맛집 · 오픈",
    businessType: "localVisit",
    industry: "restaurant",
    purpose: "newOpen",
    tone: "lifestyle",
    region: "부산 해운대",
    brandName: "한옥마을식당",
    mainKeyword: "해운대 맛집",
    subKeyword: "오픈, 예약",
    benefit: "오픈 기념 음료 서비스",
  },
  {
    id: "salon-reserve",
    label: "미용실 · 예약",
    businessType: "space",
    industry: "salon",
    purpose: "reservation",
    tone: "trust",
    region: "서울 마포구",
    brandName: "클래식바버",
    mainKeyword: "마포 미용실",
    subKeyword: "펌, 염색",
  },
];
