/**
 * 국내 마케팅팀장 30명 가상 패널 SSOT
 * 업종·채널·우선순위 다양 — 엔진/전환 토의용
 */

/** @typedef {"네이버"|"인스타"|"플레이스"|"복합"} ChannelFocus */
/** @typedef {"전환"|"신뢰"|"속도"|"브랜드일관성"|"지역성"|"측정"} Priority */

/**
 * @typedef {object} MarketingDirector
 * @property {string} id
 * @property {string} name
 * @property {string} title
 * @property {string} industry
 * @property {string} region
 * @property {"local"|"chain"|"agency"} orgType
 * @property {ChannelFocus} channelFocus
 * @property {Priority} priority
 */

/** @type {MarketingDirector[]} */
export const MARKETING_DIRECTOR_PANEL_30 = [
  {
    id: "md01",
    name: "김서연",
    title: "마케팅팀장",
    industry: "카페·F&B",
    region: "서울 마포",
    orgType: "local",
    channelFocus: "네이버",
    priority: "전환",
  },
  {
    id: "md02",
    name: "박준호",
    title: "브랜드마케팅팀장",
    industry: "음식점·외식",
    region: "부산 해운대",
    orgType: "chain",
    channelFocus: "복합",
    priority: "브랜드일관성",
  },
  {
    id: "md03",
    name: "이하늘",
    title: "디지털마케팅팀장",
    industry: "의료·클리닉",
    region: "인천 송도",
    orgType: "local",
    channelFocus: "네이버",
    priority: "신뢰",
  },
  {
    id: "md04",
    name: "최유진",
    title: "마케팅팀장",
    industry: "뷰티·피부",
    region: "서울 강남",
    orgType: "chain",
    channelFocus: "인스타",
    priority: "전환",
  },
  {
    id: "md05",
    name: "정민재",
    title: "그로스팀장",
    industry: "학원·교육",
    region: "대구 수성",
    orgType: "local",
    channelFocus: "네이버",
    priority: "측정",
  },
  {
    id: "md06",
    name: "한소희",
    title: "콘텐츠마케팅팀장",
    industry: "꽃집·선물",
    region: "경기 성남",
    orgType: "local",
    channelFocus: "인스타",
    priority: "속도",
  },
  {
    id: "md07",
    name: "오세훈",
    title: "마케팅팀장",
    industry: "숙박·펜션",
    region: "제주 애월",
    orgType: "local",
    channelFocus: "플레이스",
    priority: "지역성",
  },
  {
    id: "md08",
    name: "윤지아",
    title: "퍼포먼스팀장",
    industry: "리테일·패션",
    region: "서울 성수",
    orgType: "chain",
    channelFocus: "인스타",
    priority: "전환",
  },
  {
    id: "md09",
    name: "강태양",
    title: "마케팅팀장",
    industry: "인테리어·시공",
    region: "경기 광주",
    orgType: "local",
    channelFocus: "네이버",
    priority: "신뢰",
  },
  {
    id: "md10",
    name: "송미래",
    title: "브랜드커뮤니케이션팀장",
    industry: "가구·리빙",
    region: "경기 용인",
    orgType: "chain",
    channelFocus: "복합",
    priority: "브랜드일관성",
  },
  {
    id: "md11",
    name: "배현우",
    title: "마케팅팀장",
    industry: "자동차·정비",
    region: "대전 유성",
    orgType: "local",
    channelFocus: "네이버",
    priority: "지역성",
  },
  {
    id: "md12",
    name: "임채원",
    title: "디지털마케팅팀장",
    industry: "피트니스",
    region: "서울 영등포",
    orgType: "chain",
    channelFocus: "인스타",
    priority: "속도",
  },
  {
    id: "md13",
    name: "조은별",
    title: "마케팅팀장",
    industry: "베이커리",
    region: "광주 동구",
    orgType: "local",
    channelFocus: "플레이스",
    priority: "전환",
  },
  {
    id: "md14",
    name: "신도윤",
    title: "콘텐츠팀장",
    industry: "반려동물",
    region: "서울 송파",
    orgType: "local",
    channelFocus: "인스타",
    priority: "브랜드일관성",
  },
  {
    id: "md15",
    name: "문가영",
    title: "마케팅팀장",
    industry: "치과·의료",
    region: "부산 수영",
    orgType: "local",
    channelFocus: "네이버",
    priority: "신뢰",
  },
  {
    id: "md16",
    name: "황준서",
    title: "그로스마케팅팀장",
    industry: "이커머스",
    region: "서울 중구",
    orgType: "chain",
    channelFocus: "복합",
    priority: "측정",
  },
  {
    id: "md17",
    name: "나혜림",
    title: "마케팅팀장",
    industry: "부동산·중개",
    region: "경기 하남",
    orgType: "local",
    channelFocus: "네이버",
    priority: "신뢰",
  },
  {
    id: "md18",
    name: "유성민",
    title: "브랜드마케팅팀장",
    industry: "주류·F&B",
    region: "서울 이태원",
    orgType: "chain",
    channelFocus: "인스타",
    priority: "브랜드일관성",
  },
  {
    id: "md19",
    name: "권다은",
    title: "마케팅팀장",
    industry: "청소·설비",
    region: "대구 동구",
    orgType: "local",
    channelFocus: "네이버",
    priority: "속도",
  },
  {
    id: "md20",
    name: "홍석진",
    title: "퍼포먼스마케팅팀장",
    industry: "전문서비스·법률",
    region: "서울 서초",
    orgType: "agency",
    channelFocus: "네이버",
    priority: "신뢰",
  },
  {
    id: "md21",
    name: "서예준",
    title: "마케팅팀장",
    industry: "키즈·교육",
    region: "세종",
    orgType: "local",
    channelFocus: "인스타",
    priority: "전환",
  },
  {
    id: "md22",
    name: "노지훈",
    title: "디지털팀장",
    industry: "호텔·리조트",
    region: "강원 속초",
    orgType: "chain",
    channelFocus: "복합",
    priority: "지역성",
  },
  {
    id: "md23",
    name: "안수빈",
    title: "콘텐츠마케팅팀장",
    industry: "한의원·웰니스",
    region: "대전 서구",
    orgType: "local",
    channelFocus: "네이버",
    priority: "신뢰",
  },
  {
    id: "md24",
    name: "피도현",
    title: "마케팅팀장",
    industry: "매트리스·침구",
    region: "경기 기흥",
    orgType: "chain",
    channelFocus: "네이버",
    priority: "전환",
  },
  {
    id: "md25",
    name: "탁예린",
    title: "브랜드팀장",
    industry: "화장품·뷰티",
    region: "서울 명동",
    orgType: "chain",
    channelFocus: "인스타",
    priority: "브랜드일관성",
  },
  {
    id: "md26",
    name: "구민호",
    title: "마케팅팀장",
    industry: "프랜차이즈 본사",
    region: "서울 여의도",
    orgType: "agency",
    channelFocus: "복합",
    priority: "측정",
  },
  {
    id: "md27",
    name: "라서현",
    title: "로컬마케팅팀장",
    industry: "전통시장·소상공",
    region: "전주 완산",
    orgType: "local",
    channelFocus: "플레이스",
    priority: "지역성",
  },
  {
    id: "md28",
    name: "마준혁",
    title: "그로스팀장",
    industry: "SaaS·B2B",
    region: "판교",
    orgType: "agency",
    channelFocus: "복합",
    priority: "측정",
  },
  {
    id: "md29",
    name: "백소율",
    title: "마케팅팀장",
    industry: "웨딩·이벤트",
    region: "서울 청담",
    orgType: "local",
    channelFocus: "인스타",
    priority: "속도",
  },
  {
    id: "md30",
    name: "채우진",
    title: "퍼포먼스팀장",
    industry: "물류·배송",
    region: "인천 남동",
    orgType: "chain",
    channelFocus: "네이버",
    priority: "전환",
  },
];

export const PANEL_EVAL_AXES = [
  "engineTrust",
  "sampleValue",
  "signupFriction",
  "freeLaunchMessage",
  "nextPriority",
];

export const PANEL_CONSENSUS_FIXED = {
  adoptedToday: {
    id: "signup_conversion_mobile_free_cta",
    title: "맛보기→가입 전환: 모바일 CTA 노출 + 무료·브랜드 이어가기 카피",
    rationale:
      "CTA 클릭은 있으나 외부 가입이 정체. 모바일에서 결과 CTA가 숨겨지고 sticky가 '저장'에 머물러 가치·무료가 약함.",
  },
  deferred: [
    {
      id: "carry_preview_to_workspace",
      title: "맛보기 본문 전체를 가입 후 워크스페이스로 이관",
      reason: "범위 큼 — 다음 스프린트",
    },
    {
      id: "engine_category_patch",
      title: "엔진·카테고리 품질 대패치",
      reason: "free launch KPI(실사용자 전환)와 불일치",
    },
  ],
};
