/**
 * BRICLOG MASTER QUALITY DIRECTIVE — V20 SSOT re-export
 * @see lib/product/briclogUltimateV20.js
 */
export {
  BRICLOG_ULTIMATE_VERSION as MASTER_QUALITY_DIRECTIVE_VERSION,
  PRODUCT_POSITION,
  QUALITY_PRIORITIES,
  FORBIDDEN_FAST_PATH,
  CONTENT_PIPELINE_ORDER,
  CONTENT_PIPELINE_LABELS,
  INFORMATION_UNIT_RANGE,
  BLOG_LENGTH_TIERS,
  DUPLICATE_POLICY,
  STRUCTURE_DUPLICATE_POLICY,
  HUMAN_DUPLICATE_POLICY,
  EDITOR_COLUMN_STRUCTURE,
  MASTER_FINAL_REVIEW,
  INTERNAL_OUTPUT_BANNED_SNIPPETS,
  TITLE_ENGINE_RULES,
  CHANNEL_ENGINE_RULES,
  EMOJI_CHANNEL_DEFAULTS,
  MASTER_QUALITY_POSITIONING_BRIEF,
  MASTER_QUALITY_EDITOR_BRIEF,
  MASTER_QUALITY_GUARD_BRIEF,
  buildMasterQualityPromptBlock,
  buildUltimateV20PromptBlock,
  requiresMasterQualityPipeline,
} from "@/lib/product/briclogUltimateV20";
