export {
  BRAND_PHILOSOPHY,
  BRICLOG_SLOGAN_SHORT,
  LANDING_CTA_FOOTNOTE,
  LANDING_CTA_HEADLINE,
  LANDING_CTA_PHILOSOPHY,
  LANDING_CTA_SUB,
  LANDING_HERO_DEFAULT,
  LANDING_HERO_MOBILE_TRUST,
  LANDING_PRIMARY_CTA,
  LANDING_SECONDARY_CTA,
  LANDING_PRICING_INTRO,
  LANDING_PRICING_SUB,
} from "@/lib/brand/copy";

export { DEVICE_BENEFIT as LANDING_DEVICE_HINTS } from "@/lib/workspace/devicePreviewCopy";
