export {
  BRAND_PHILOSOPHY,
  BRICLOG_SLOGAN_SHORT,
  LANDING_CTA_FOOTNOTE,
  LANDING_CTA_HEADLINE,
  LANDING_CTA_PHILOSOPHY,
  LANDING_CTA_SUB,
  LANDING_FOOTER_SIGNUP_CTA,
  LANDING_HERO_DEFAULT,
  LANDING_HERO_MOBILE_TRUST,
  LANDING_LOGIN_CTA,
  LANDING_LOGIN_HINT,
  LANDING_NAV_SIGNUP_CTA,
  LANDING_NAV_START_CTA,
  LANDING_PRIMARY_CTA,
  LANDING_PRIMARY_SUB,
  LANDING_SECONDARY_CTA,
  LANDING_PRICING_INTRO,
  LANDING_PRICING_SUB,
  PUBLIC_TEST_STICKY_SIGNUP_CTA,
  PUBLIC_TEST_STICKY_SIGNUP_HEADLINE,
} from "@/lib/brand/copy";

export { DEVICE_BENEFIT as LANDING_DEVICE_HINTS } from "@/lib/workspace/devicePreviewCopy";
